# Generated by Django 4.2.3 on 2023-07-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название категории ингредиентов')),
                ('optional', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категории ингредиентов',
                'verbose_name_plural': 'Категории ингредиентов',
            },
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Tорт', 'verbose_name_plural': 'Tорты'},
        ),
        migrations.AlterModelOptions(
            name='deliverytime',
            options={'verbose_name': 'Время доставки', 'verbose_name_plural': 'Время доставки'},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'Тип доставки', 'verbose_name_plural': 'Типы доставки'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='picture',
            field=models.ImageField(upload_to='ingredients', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='cakes.ingredientcategory', verbose_name='Категория'),
        ),
    ]
