# Generated by Django 4.2.3 on 2023-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_alter_cake_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cakes', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес'),
        ),
    ]
