# Generated by Django 4.2.3 on 2023-07-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_alter_cake_description_alter_cake_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cakes.cake', verbose_name='Торт'),
        ),
        migrations.CreateModel(
            name='OrderIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cakes.ingredients', verbose_name='Ингредиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cakes.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Ингредиенты заказа',
                'verbose_name_plural': 'Ингредиенты заказа',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(through='cakes.OrderIngredients', to='cakes.ingredients', verbose_name='Ингредиенты'),
        ),
    ]
