# Generated by Django 4.2.3 on 2023-07-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_alter_cake_description_alter_cake_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='picture',
            field=models.ImageField(null=True, upload_to='cakes', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cakes.cake', verbose_name='Торт'),
        ),
    ]
