# Generated by Django 4.2.3 on 2023-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_alter_cake_picture_alter_deliverytime_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='personal_data_consent_date',
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
